### ISSUE TITLE
https://www.nodejs-security.com/blog/do-not-use-secrets-in-environment-variables-and-here-is-how-to-do-it-better

### ISSUE THREAD

**Issue by siosio34** [Korean-FE-Article/article-recommendation#168]
https://www.nodejs-security.com/blog/do-not-use-secrets-in-environment-variables-and-here-is-how-to-do-it-better
## ⚠️ 이슈를 올리기 전 체크해주세요! ⚠️

- [X] 이슈 제목은 링크로 하셨나요?
- [X] 본문에도 이슈 링크를 추가해주세요: https://www.nodejs-security.com/blog/do-not-use-secrets-in-environment-variables-and-here-is-how-to-do-it-better
- [X] 이미 누군가 추천하지 않았나요? 만약 이미 추천한 글이 있다면 이슈를 올리는 대신 해당 이슈에 이모지나 댓글을 남겨 주세요!
- [X] 이미 번역된 글이 있는지 확인하셨나요? 이미 번역된 중복된 글이 있다면, 번역하지 않습니다.

### 선택 사항

- [X] 이 글이 번역되면 메일 하단에 추천인의 Github 아이디와 링크를 노출합니다. 이 부분 괜찮으신가요?

**Comment by siosio34** [comment]
추천은 했지만 다음 번역타임때 제가 번역하고싶슴다

**Comment by jung-han** [comment]
ㅋㅋㅋ그럼 여기에 안올리셔도 됩니다 
여기 있는 글은 누구나 시작해도 괜찮다여서요 ㅎㅎ
저렇게 올리시면 사실상 여러 글을 갖고 계신거나 마찬가지시니 차라리 안올리시는걸로...
보시면 이슈 닫아주세요~

**Comment by siosio34** [comment]
앗 바로 닫을게요!

**Comment by siosio34** [comment]
당장 번역할거 아니면 글 잡아놓는거 안하도록 하겠습니다!
